export const TOP_RATED_MOVIES_REQUEST = 'TOP_RATED_MOVIES_REQUEST'
export const TOP_RATED_MOVIES_SUCCESS = 'TOP_RATED_MOVIES_SUCCESS'
export const TOP_RATED_MOVIES_FAIL = 'TOP_RATED_MOVIES_FAIL'

export const NEW_MOVIES_REQUEST = 'NEW_MOVIES_REQUEST'
export const NEW_MOVIES_SUCCESS = 'NEW_MOVIES_SUCCESS'
export const NEW_MOVIES_FAIL = 'NEW_MOVIES_FAIL'

export const POPULAR_MOVIES_REQUEST = 'POPULAR_MOVIES_REQUEST'
export const POPULAR_MOVIES_SUCCESS = 'POPULAR_MOVIES_SUCCESS'
export const POPULAR_MOVIES_FAIL = 'POPULAR_MOVIES_FAIL'

export const UPCOMING_MOVIES_REQUEST = 'UPCOMING_MOVIES_REQUEST'
export const UPCOMING_MOVIES_SUCCESS = 'UPCOMING_MOVIES_SUCCESS'
export const UPCOMING_MOVIES_FAIL = 'UPCOMING_MOVIES_FAIL'

export const MOVIE_DETAIL_REQUEST = 'MOVIE_DETAIL_REQUEST'
export const MOVIE_DETAIL_SUCCESS = 'MOVIE_DETAIL_SUCCESS'
export const MOVIE_DETAIL_FAIL = 'MOVIE_DETAIL_FAIL'

export const MOVIE_CREDITS_REQUEST = 'MOVIE_CREDITS_REQUEST'
export const MOVIE_CREDITS_SUCCESS = 'MOVIE_CREDITS_SUCCESS'
export const MOVIE_CREDITS_FAIL = 'MOVIE_CREDITS_FAIL'

export const MOVIE_TRAILER_REQUEST = 'MOVIE_TRAILER_REQUEST'
export const MOVIE_TRAILER_SUCCESS = 'MOVIE_TRAILER_SUCCESS'
export const MOVIE_TRAILER_FAIL = 'MOVIE_TRAILER_FAIL'

export const SIMILAR_MOVIES_REQUEST = 'SIMILAR_MOVIES_REQUEST'
export const SIMILAR_MOVIES_SUCCESS = 'SIMILAR_MOVIES_SUCCESS'
export const SIMILAR_MOVIES_FAIL = 'SIMILAR_MOVIES_FAIL'

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST'
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS'
export const SEARCH_MOVIES_FAIL = 'SEARCH_MOVIES_FAIL'
export const SEARCH_MOVIES_RESET = 'SEARCH_MOVIES_RESET'